### ISSUE TITLE
Question about duktape

### ISSUE THREAD

**Issue by owl4ce** [ferion11/danrepo#5]
Hi, thanks in advance. I like your work.

I just want to ask. What's the difference between `duktape` from here and the official Gentoo's repo?
Currently I use `brave-bin`, `polkit`, and `duktape` from danrepo.

**Comment by ferion11** [comment]
> Hi, thanks in advance. I like your work.
> 
> I just want to ask. What's the difference between `duktape` from here and the official Gentoo's repo?
> Currently I use `brave-bin`, `polkit`, and `duktape` from danrepo.

It's almost the same, but because of this https://github.com/ferion11/danrepo/issues/2 bug, I had to add a flag for debugging and another to manual include libm (for those having the same issue), although for me, in my machine,, the two are the same (USE="cmdline -debug -libm" works for me)

**Comment by owl4ce** [comment]
Thank you for answering. I suggest enabling the `discussion` feature in this repo's settings.

**Comment by owl4ce** [comment]
![2021-05-19-094817_602x267_scrot](https://user-images.githubusercontent.com/53987136/118751967-743cb580-b88c-11eb-9dde-976abc4b1a0d.png)

<h2></h2>

Hi, I had this when there was a rule using a format like below (although by default too)
```sh
polkit.addAdminRule(function(action, subject) {
    return ["unix-group:wheel"];
});

polkit.addAdminRule(function(action, subject) {
    return ["unix-user:0"];
});
```
in `/etc/polkit-1/rules.d/*`

So I have to remove the above formatted rule so that it can be authenticated as root, as a result I can't set certain groups to get rights too. **Any solution?**

**Comment by owl4ce** [comment]
I guess is it because of using `duktape` as the build dependency? Because I tried to go back to using `spidermonkey`, and it worked.

**Comment by owl4ce** [comment]
I guess is it because of using `duktape` as the build dependency? Because I tried to go back to using `spidermonkey`, and it worked.

**Comment by owl4ce** [comment]
> ![2021-05-19-094817_602x267_scrot](https://user-images.githubusercontent.com/53987136/118751967-743cb580-b88c-11eb-9dde-976abc4b1a0d.png)
> 
> Hi, I had this when there was a rule using a format like below (although by default too)
> 
> ```shell
> polkit.addAdminRule(function(action, subject) {
>     return ["unix-group:wheel"];
> });
> 
> polkit.addAdminRule(function(action, subject) {
>     return ["unix-user:0"];
> });
> ```
> 
> in `/etc/polkit-1/rules.d/*`
> 
> So I have to remove the above formatted rule so that it can be authenticated as root, as a result I can't set certain groups to get rights too. **Any solution?**

Oh, idk whats happen. Now solved in my new Gentoo system.
