### ISSUE TITLE
`www-client/brave-bin`: `crashpad_handler` require execute permission

### ISSUE THREAD

**Issue by owl4ce** [ferion11/danrepo#6]
I forgot since which version, in my system, it needs to do as in the title above.
```sh
doas chmod +x /opt/brave/crashpad_handler
```
If not then got this output .. (stuck there)
```log
[13114:13114:0807/110116.176760:FATAL:double_fork_and_exec.cc(131)] execv /opt/brave/crashpad_handler: Permission denied (13)
```

**I want to confirm is this happening on your system?** If yes then make changes to the `www-client/brave-bin` ebuild.

Thank you.

**Comment by owl4ce** [comment]
Also, would be good if to enable **hardware video decoding** by default.

**X11:** ` --use-gl=desktop --enable-features=VaapiVideoDecoder`
**XWayland:** ` --use-gl=egl --enable-features=VaapiVideoDecoder`

`/usr/share/applications/brave-bin.desktop`
```desktop
[Desktop Entry]
Name=Brave
Comment=Brave Web Browser
Exec=/usr/bin/brave-bin --use-gl=desktop --enable-features=VaapiVideoDecoder %u
Icon=brave-bin
Terminal=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
Categories=Network;WebBrowser;
```

https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html

**Comment by ferion11** [comment]
Fixed on: https://github.com/ferion11/danrepo/commit/4ac2763bf6c612456b9140903825f54b10557fa9
